In [2]:
import pandas as pd
student_info = pd.read_csv("studentInfo.csv")
print(student_info)

      code_module code_presentation  id_student gender                region  \
0             AAA             2013J       11391      M   East Anglian Region
1             AAA             2013J       28400      F              Scotland
2             AAA             2013J       30268      F  North Western Region
3             AAA             2013J       31604      F     South East Region
4             AAA             2013J       32885      F  West Midlands Region
...           ...               ...         ...    ...                   ...
32588         GGG             2014J     2640965      F                 Wales
32589         GGG             2014J     2645731      F   East Anglian Region
32590         GGG             2014J     2648187      F          South Region
32591         GGG             2014J     2679821      F     South East Region
32592         GGG             2014J     2684003      F      Yorkshire Region

           highest_education imd_band age_band  num_of_prev_attempts  \
0           HE Qualification  90-100%     55<=                     0
1           HE Qualification   20-30%    35-55                     0
2      A Level or Equivalent   30-40%    35-55                     0
3      A Level or Equivalent   50-60%    35-55                     0
4         Lower Than A Level   50-60%     0-35                     0
...                      ...      ...      ...                   ...
32588     Lower Than A Level    10-20     0-35                     0
32589     Lower Than A Level   40-50%    35-55                     0
32590  A Level or Equivalent   20-30%     0-35                     0
32591     Lower Than A Level  90-100%    35-55                     0
32592       HE Qualification   50-60%    35-55                     0

       studied_credits disability final_result
0                  240          N         Pass
1                   60          N         Pass
2                   60          Y    Withdrawn
3                   60          N         Pass
4                   60          N         Pass
...                ...        ...          ...
32588               30          N         Fail
32589               30          N  Distinction
32590               30          Y         Pass
32591               30          N    Withdrawn
32592               30          N  Distinction

[32593 rows x 12 columns]

In [4]:
import os
print(os.getcwd())

C:\Users\Abhigya Rai\Downloads\EWS

In [7]:
print(student_info.head())

  code_module code_presentation  id_student gender                region  \
0         AAA             2013J       11391      M   East Anglian Region
1         AAA             2013J       28400      F              Scotland
2         AAA             2013J       30268      F  North Western Region
3         AAA             2013J       31604      F     South East Region
4         AAA             2013J       32885      F  West Midlands Region

       highest_education imd_band age_band  num_of_prev_attempts  \
0       HE Qualification  90-100%     55<=                     0
1       HE Qualification   20-30%    35-55                     0
2  A Level or Equivalent   30-40%    35-55                     0
3  A Level or Equivalent   50-60%    35-55                     0
4     Lower Than A Level   50-60%     0-35                     0

   studied_credits disability final_result
0              240          N         Pass
1               60          N         Pass
2               60          Y    Withdrawn
3               60          N         Pass
4               60          N         Pass

In [8]:
print(student_info.info())

<class 'pandas.DataFrame'>
RangeIndex: 32593 entries, 0 to 32592
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   code_module           32593 non-null  str
 1   code_presentation     32593 non-null  str
 2   id_student            32593 non-null  int64
 3   gender                32593 non-null  str
 4   region                32593 non-null  str
 5   highest_education     32593 non-null  str
 6   imd_band              31482 non-null  str
 7   age_band              32593 non-null  str
 8   num_of_prev_attempts  32593 non-null  int64
 9   studied_credits       32593 non-null  int64
 10  disability            32593 non-null  str
 11  final_result          32593 non-null  str
dtypes: int64(3), str(9)
memory usage: 4.8 MB
None

In [5]:
print(student_info.shape)

(32593, 12)

In [6]:
display(student_info)

,code_module,code_presentation,id_student,gender,region,highest_education,imd_band,age_band,num_of_prev_attempts,studied_credits,disability,final_result
0,AAA,2013J,11391,M,East Anglian Region,HE Qualification,90-100%,55<=,0,240,N,Pass
1,AAA,2013J,28400,F,Scotland,HE Qualification,20-30%,35-55,0,60,N,Pass
2,AAA,2013J,30268,F,North Western Region,A Level or Equivalent,30-40%,35-55,0,60,Y,Withdrawn
3,AAA,2013J,31604,F,South East Region,A Level or Equivalent,50-60%,35-55,0,60,N,Pass
4,AAA,2013J,32885,F,West Midlands Region,Lower Than A Level,50-60%,0-35,0,60,N,Pass
...,...,...,...,...,...,...,...,...,...,...,...,...
32588,GGG,2014J,2640965,F,Wales,Lower Than A Level,10-20,0-35,0,30,N,Fail
32589,GGG,2014J,2645731,F,East Anglian Region,Lower Than A Level,40-50%,35-55,0,30,N,Distinction
32590,GGG,2014J,2648187,F,South Region,A Level or Equivalent,20-30%,0-35,0,30,Y,Pass
32591,GGG,2014J,2679821,F,South East Region,Lower Than A Level,90-100%,35-55,0,30,N,Withdrawn
32592,GGG,2014J,2684003,F,Yorkshire Region,HE Qualification,50-60%,35-55,0,30,N,Distinction

In [8]:
column_names = list(student_info.columns)
display(column_names)

['code_module',
 'code_presentation',
 'id_student',
 'gender',
 'region',
 'highest_education',
 'imd_band',
 'age_band',
 'num_of_prev_attempts',
 'studied_credits',
 'disability',
 'final_result']

In [9]:
display(student_info['final_result'])

0               Pass
1               Pass
2          Withdrawn
3               Pass
4               Pass
            ...
32588           Fail
32589    Distinction
32590           Pass
32591      Withdrawn
32592    Distinction
Name: final_result, Length: 32593, dtype: str

In [10]:
final_result_count = student_info['final_result'].value_counts()
display(final_result_count)

final_result
Pass           12361
Withdrawn      10156
Fail            7052
Distinction     3024
Name: count, dtype: int64

In [11]:
missing_value = student_info.isnull().sum()
print(missing_value)

code_module                0
code_presentation          0
id_student                 0
gender                     0
region                     0
highest_education          0
imd_band                1111
age_band                   0
num_of_prev_attempts       0
studied_credits            0
disability                 0
final_result               0
dtype: int64

In [12]:
student_info['Potential dropout students'] = (student_info['final_result'] == 'Withdrawn').astype(int)
display(student_info['Potential dropout students'])

0        0
1        0
2        1
3        0
4        0
        ..
32588    0
32589    0
32590    0
32591    1
32592    0
Name: Potential dropout students, Length: 32593, dtype: int64

In [13]:
display(student_info)

,code_module,code_presentation,id_student,gender,region,highest_education,imd_band,age_band,num_of_prev_attempts,studied_credits,disability,final_result,Potential dropout students
0,AAA,2013J,11391,M,East Anglian Region,HE Qualification,90-100%,55<=,0,240,N,Pass,0
1,AAA,2013J,28400,F,Scotland,HE Qualification,20-30%,35-55,0,60,N,Pass,0
2,AAA,2013J,30268,F,North Western Region,A Level or Equivalent,30-40%,35-55,0,60,Y,Withdrawn,1
3,AAA,2013J,31604,F,South East Region,A Level or Equivalent,50-60%,35-55,0,60,N,Pass,0
4,AAA,2013J,32885,F,West Midlands Region,Lower Than A Level,50-60%,0-35,0,60,N,Pass,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
32588,GGG,2014J,2640965,F,Wales,Lower Than A Level,10-20,0-35,0,30,N,Fail,0
32589,GGG,2014J,2645731,F,East Anglian Region,Lower Than A Level,40-50%,35-55,0,30,N,Distinction,0
32590,GGG,2014J,2648187,F,South Region,A Level or Equivalent,20-30%,0-35,0,30,Y,Pass,0
32591,GGG,2014J,2679821,F,South East Region,Lower Than A Level,90-100%,35-55,0,30,N,Withdrawn,1
32592,GGG,2014J,2684003,F,Yorkshire Region,HE Qualification,50-60%,35-55,0,30,N,Distinction,0

In [1]:
#code_module = The code of the course
#course_presentation = 2013J, the course started in 2013 and J means October as B is January
#imd_band = How deprived or poor the student's home area is. 0-10% is the most deprived whereas 90-100% is the least deprived.
#num_of_prev_attempts = How many times has the student taken this course before
#studied_credits = It measures the workload of the student. More credits means they have taken multiple courses. A student is likely to withdraw from a course if they have heavier workload.